not run - Removed the options.AllowAreas to solve the error -->Severity Code Description Project File Line Suppression State Error CS1061 'RazorPagesOptions' does not contain a definition for 'AllowAreas' and no accessible extension method 'AllowAreas' accepting a first argument of type 'RazorPagesOptions' could be found (are you missing a using directive or an assembly reference?) TagHelpersBuiltIn C:\Users\pradeep.singh\source\repos\_TagHelpersBuiltIn\Startup.cs 32 Active